# -*- coding: utf-8 -*-
"""Assignment 1 | 6th February 2021 | python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oGSWSPfbJXyC2gmzm9_fMKzx9P_4DNC_

### List
"""

ls=[1,2,3,5,4,89,"Lets updrade",45,2,5,8,5,8,["89,6,5,2,6"],5,8,5,5]
print(ls)

ls.append("7")
ls

ls.count(89)

ls.insert(2,65)
ls

ls=[1,2,3,5,4,89,"Lets updrade",45,2,5,8,5,8,["89,6,5,2,6"],5,8,5,5]
print(ls)

ls.pop(4)
ls

ls.clear()
ls

"""# Dictionary

"""

dit = {"Name": "Rohit", "class": "12th","Aim":"Softwaere Dveloper","Loc":"Haryana"}
print(dit)

print(dit['Name'])

print(dit['Loc'])

print(dit['Aim'])

print(dit.keys)

marks ={'Math':98, 'English':89, 'Science':96}
print(marks)

print(marks['Math'])

odd_squares = {x: x*x for x in range(11) if x % 2 == 1}

print(odd_squares)

